#!/usr/bin/env python

"""Automatically set local timezone based on IP geolocation."""

import errno
import argparse
import json
import os
import sys
import urllib


zoneinfo_path = "/usr/share/zoneinfo"
localtime_path = "/etc/localtime"


def location_from_ip():
    """
    Return location data for an IP using the IPInfoDB API.

    :returns: latitude and longitude
    """

    url = "http://api.ipinfodb.com/v3/ip-city/?"
    url_params = {
        "key": "c253fddcfa96b60155aa66fb51b20cba"
               "dbcfa2020b2d27a89d4554ac2799b935",
        "format": "json",
    }

    res_handle = urllib.urlopen(url + urllib.urlencode(url_params))
    res_data = json.load(res_handle)

    coords = {
        "latitude": res_data["latitude"],
        "longitude": res_data["longitude"],
    }

    return coords


def timezone_from_location(coords):
    """
    Return the timezone for a set of coordinates using the GeoNames API.

    :param coords: latitude and longitude
    :returns: timezone
    """

    url = "http://api.geonames.org/timezoneJSON?"
    url_params = {
        "username": "tzupdate",
        "lat": coords["latitude"],
        "lng": coords["longitude"],
    }

    res_handle = urllib.urlopen(url + urllib.urlencode(url_params))
    res_data = json.load(res_handle)

    timezone = res_data["timezoneId"]

    return timezone


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "-p", "--print-only",
        action="store_true",
        help="print the timezone only, don't update the localtime symlink"
    )
    args = parser.parse_args()

    coords = location_from_ip()
    timezone = timezone_from_location(coords)

    if not args.print_only:
        timezone_path = os.path.join(zoneinfo_path, timezone)
        if not os.path.isfile(timezone_path):
            print >> sys.stderr, "Unknown timezone: " + timezone_path

        try:
            os.unlink(localtime_path)
        except OSError, e:
            if e.errno != errno.ENOENT:
                raise

        os.symlink(timezone_path, localtime_path)

    print timezone
